### ISSUE TITLE
프로젝트 주제 확정 및 계획 수립

### ISSUE THREAD

**Issue by KangJiUng** [Hyunjiiing/OSS-TeamProject2#1]
주제를 확정하고 중간 발표까지의 계획을 수립합니다.

**Comment by KangJiUng** [comment]
다이어트 도우미와 데이트 도우미 중 어떤 프로젝트를 메인으로 잡을지 정해봅시당 의견이 있을까요?

**Comment by Hyunjiiing** [comment]
저는 다이어트 도우미 프로젝트가 기존의 다이어트 앱들에게는 없는 참신한 아이디어 인 거 같아 좋은거 같습니다!

**Comment by KangJiUng** [comment]
저도 다이어트 도우미가 좋은 것  같습니다! 그럼 저희 프로젝트는 다이어트 도우미로 결정하겠습니다

**Comment by Hyunjiiing** [comment]
네! 좋아요. 혹시 저희 레포지토리 이름을 프로젝트 주제에 맞게 변경하는거 어떠세요? 저는 분석하고 예측하는게 주이니까 binge-prediction-analysis-python 가 좋을거 같아요. 또 다른 의견 있을까용

**Comment by KangJiUng** [comment]
엇 좋은데 조금만 짧아지면 좋겠는데... 아니면 저희 프로젝트의 이름이 제대로 정해진 뒤에 바꾸는 건 어떨까요?

**Comment by Hyunjiiing** [comment]
오 좋습니다!

**Comment by KangJiUng** [comment]
네 그러면 프로젝트 계획 수립 단계로 넘어가 볼게요. 우선 웹/앱 을 정하고 언어를 확실히 하면 좋을 것 같은데 혹시 경험이 있거나 하고 싶은 방향이 있으실까요?

**Comment by Hyunjiiing** [comment]
저는 웹/앱 둘다 경험해본적이 있는데 다이어트 관련이니까 앱이 더 접근하기 좋을거 같아서 앱이 좋은거 같습니다. 앱으로 프론트 : flutter 혹은 react, 백엔드 : python으로 하면 어떨까요?

**Comment by KangJiUng** [comment]
좋습니다! 그럼 우선 진행 중에 차질이 생기지 않는 이상 사용 언어는 그렇게 적용하도록  할게요. 본격적인 계획에 들어가기 전, 다이어트 앱을 더 자세히 구상해봅시다!

**Comment by Hyunjiiing** [comment]
넵! 타사 다이어트 앱들을 참고해보는건 어떨까요? 혹시 사용해보신 다이어트 어플 있으신가요? 저는 DANO라는 어플을 사용해봤는데 그것을 위주로 분석해보겠습니다!

**Comment by KangJiUng** [comment]
앱 구상에 대한 이슈를 따로 만들어서 대화를 나누면 좋을 것 같아요! 현지님이 이슈 만들어주시면 거기에서 뵐게요 ㅎ

**Comment by Hyunjiiing** [comment]
넵! 이따봬요

**Comment by KangJiUng** [comment]
그럼 저희 다음주(4월 10일)부터 1주차로 설정해서 주차별로 계획 수립 해볼게요

**Comment by Hyunjiiing** [comment]
넵!

**Comment by LSA31** [comment]
네

**Comment by KangJiUng** [comment]
일단 앞서 정했던 역할 분배가 

- 폭식 타이밍 분석 및 예측, 월경 기록
- 폭식 타이밍에 경고 알림 보내기
-----------------------------------------------
- 식단과 운동 루틴 입력하면 발생할 효과 예측
- 식단 운동 루틴 예측 결과 서비스 제공
- 캐릭터 육성
-----------------------------------------------
- 식재료 입력 시 다이어트 식단 레시피 추천
- 물/컨디션/영양제 기록
- 체중 또는 칼로리 그래프, 캘린더뷰

이니까 각 기능별로 조금 더 세세하게 나눠서 계획하면 좋을 것 같아요

**Comment by KangJiUng** [comment]
우선 각자가 맡은 부분들 세세하게 나눠서 정리해봅시다

**Comment by Hyunjiiing** [comment]
저희 개발 끝나는 날이 언제이드라요

**Comment by Hyunjiiing** [comment]
10주정도 남은거 같아요

**Comment by LSA31** [comment]
물/컨디션/영양제 기록 부분은 사용자가 직접 입력하는 부분인가요?

**Comment by Hyunjiiing** [comment]
그럼 대략적으로 7주 동안 코드 완성하고 3주동안 오류수정 및 발표준비 하면 되지 않을까요 넘 범위가 넓나여

**Comment by Hyunjiiing** [comment]
네 그렇습니다요

**Comment by LSA31** [comment]
적당한 것 같습니당

**Comment by KangJiUng** [comment]
> 그럼 대략적으로 7주 동안 코드 완성하고 3주동안 오류수정 및 발표준비 하면 되지 않을까요 넘 범위가 넓나여

아뇨 그렇게 하고 시간 여유 봐가면서 1~2주 유동적으로 진행합시다

**Comment by LSA31** [comment]
넵 좋습니다요

**Comment by KangJiUng** [comment]
1. 각종 식단과 운동 데이터 수집 및 정리
2. 식단 조합 및 운동 루틴의 기대효과 데이터 수집 및 정리
3. 식단 및 운동 루틴 입력시 저장된 데이터와 매칭시키는 기능 구현
4. 매칭된 결과를 리스트업하고 기간 짧은 순, 칼로리 소모 순 등으로 순서 정리하는 기능 구현
5. 식단 운동 루틴의 결과를 예측하는 알고리즘 구현
6. 루틴의 결과 예측 서비스 구현
7. 캐릭터 디자인 구상
8. 특정 요소에 따라 캐릭터가 성장할 수 있는 알고리즘 구현

더 세세하게는 제가 실행으로 옮기면서 나눌 수 있을 것 같고 주차별로 계획할 수 있는 건 이정도인 것 같네여

**Comment by Hyunjiiing** [comment]
[2022040028 오현지 오픈소스기초프로젝트 계획]
1주차 - 개발환경 세팅 및 예측에 필요한 자료 수집 및 중간 발표 준비
2주차 - 앱 UI 구성 및 예측 개발 및 중간 발표 준비
3주차 - 앱 UI 보안 및 예측 개발 / 앱 실행중 알람 구현
4주차 - 예측 개발
5주차 - 앱 실행중 알람 구현 
6주차 - 앱 실행 안할때 알람 구현
7주차 - 만들었던 기능들을 합치고 부족한 코드 작성

8주차 - 팀원들 기능 합치기 및 서로 오류나 보완할 부분
9주차 - 발표준비 & 보완
10주차 - 발표준비 & 보완

**Comment by Hyunjiiing** [comment]
앗.. 이렇게 짜는줄..알았어요

**Comment by KangJiUng** [comment]
> [2022040028 오현지 오픈소스기초프로젝트 계획] 1주차 - 개발환경 세팅 및 예측에 필요한 자료 수집 및 중간 발표 준비 2주차 - 앱 UI 구성 및 예측 개발 및 중간 발표 준비 3주차 - 앱 UI 보안 및 예측 개발 / 앱 실행중 알람 구현 4주차 - 예측 개발 5주차 - 앱 실행중 알람 구현 6주차 - 앱 실행 안할때 알람 구현 7주차 - 만들었던 기능들을 합치고 부족한 코드 작성
> 
> 8주차 - 팀원들 기능 합치기 및 서로 오류나 보완할 부분 9주차 - 발표준비 & 보완 10주차 - 발표준비 & 보완

이건 나중에 ppt 만들면 개인별 말고 전체적인 계획 보여줄 때 사용합시다

**Comment by Hyunjiiing** [comment]
저도 저렇게 하고 실행하면서 앞뒤로 1주는 변동될 수 있을거 같습니당 (발표날 제외)

**Comment by Hyunjiiing** [comment]
네 좋아용

**Comment by LSA31** [comment]
1. 다이어트 식단 레시피 데이터, 각 식단별 필요 식재료 데이터들 수집
2. 식재료 입력 시 레시피 추천 코드 구현
3. 다이어트 할 때 필요한 물의 양과 컨디션에 따른 대처법, 좋은 영양제 데이터들 수집
4. 물/컨디션/영양제 입력 시 어떤 자료를 제공할지 계획
5. 물/컨디션/영양제 기록 코드 구현
6. 그동안의 체중 감소와 그래프 데이터들을 통해 일정 기간 내에 얼마나 감량 가능한지 예측
7. 체중 또는 칼로리 그래프, 캘린더뷰 코드 구현

오류 발생시 문제 해결

**Comment by LSA31** [comment]
이런 식으로 계획했고  데이터 수집을 최대한 빨리 해서 그만큼 코드 구현에 시간을 더 투자하려고 합니당

**Comment by KangJiUng** [comment]
넹 좋습니다 그럼 각자는 이렇게 하고 중간중간 메인으로 커밋 assign 승인 요청하기 전에 꼭 이슈 하나씩 적어주시고 진행해주세요!! 너무 사소한 것만 제외하고 관련한 건 웬만해서 이슈로 질문하고 대답하면 좋을 것 같아용 발표 준비는 1주 반 뒤쯤부터 이슈로 또 계획합시다

**Comment by KangJiUng** [comment]
이슈는 닫겠습니다 (_ _)

**Comment by LSA31** [comment]
수고하셨습니당!
