### ISSUE TITLE
중간 발표 계획

### ISSUE THREAD

**Issue by LSA31** [Hyunjiiing/OSS-TeamProject2#10]
중간 발표 계획을 짜봅시다.

**Comment by LSA31** [comment]
분량 7~8분
필요성
Problem
차별성
Solution
추진방법및일정

**Comment by KangJiUng** [comment]
처음 발표 대본에 적었던 내용입니다. 필요성으로 정리하면 될 것 같아용

요즘 트렌드에는 관리가 필수적으로 많은 관심을 받고 있습니다. 저희는 그중 다이어트 성공에 도움이 되고자 프로젝트를 계획하게 되었습니다. 다이어트를 시도하는 사람은 매우 많지만 성공하는 사람은 극히 드문데요. 이는 동기부여가 갈수록 떨어지기 때문이라고 생각합니다. 절제력을 잃고 식단을 포기할 것 같은 사용자의 순간을 분석하고 예측해 우리 다이어트 도우미가 경고 알림을 날려줌으로써 누군가와 함께 다이어트를 하는 것과 같은 효과를 얻을 수 있도록 할 것입니다. 또한 입력한 식단과 운동 루틴의 효과를 예측하는 서비스 또한 포함시켜 다이어트의 동기부여와 정보 제공으로 보다 편리하고 유용한 앱을 개발하고자 합니다.

**Comment by KangJiUng** [comment]
각자 작성한 요구사항 명세서에서 따온 이슈사항 취합했습니다 이 부분은 problem으로 정리하면 될 것 같아용

폭식할만한 상황을 학습시킬 데이터들을 어디에서 가져올 것인가
앱 사용 중과 안할때 알람을 구별하여 구현할 수 있는가
사용자로부터 입력받은 데이터를 보관할 수 있는가
장기간 데이터가 쌓이면 앱의 속도, database에 저장 공간 등의 문제가 생길 수 있는데 어떻게 해결할 것인가
식단과 운동의 효과의 신뢰성
방대한 양의 데이터
사용자의 건강 상태에 따른 위험가능성 매칭의 복잡함
사용자의 입력값과 데이터베이스의 값의 일치성
캐릭터 디자인은 어떻게 할 것인가
육성 단계마다 캐릭터의 모습을 변화시킬 것인가
육성에 반영되는 데이터의 양은 어떻게 관리할 것인가
다양한 식재료가 사용되는 다이어트 식단 레시피 데이터들을 수집할 수 있는가
입력 받은 물/컨디션/영양제 데이터들을 저장할 수 있는가
입력받은 체중과 식단 데이터들을 저장할 수 있고 그래프화 할 수 있는가

**Comment by KangJiUng** [comment]
차별성은 폭식알람, 캐릭터 육성 기능 정도가 되겠네영

**Comment by Hyunjiiing** [comment]
예측 관점으로 차별성이 있어야 하니 다른 타사 다이어트 앱들 비교하면서 폭식알람 이런거 하면 될듯여 캐릭터 육성은 차별성은 못할듯.. 이미 있는 앱이 있어여

**Comment by KangJiUng** [comment]
솔루션도 요구사항 명세서에서 빼와서 하면 될 것 같고욤 추진 방법 및 일정을 표로 만들면 좋겠네유!

**Comment by KangJiUng** [comment]
> 예측 관점으로 차별성이 있어야 하니 다른 타사 다이어트 앱들 비교하면서 폭식알람 이런거 하면 될듯여 캐릭터 육성은 차별성은 못할듯.. 이미 있는 앱이 있어여

허거거걱 그러네요 혹시나 캐릭터 육성을 차별성으로 두려면 뭔가 더 구체적인 요소를 넣으면 좋을 것 같으네용

**Comment by Hyunjiiing** [comment]
1)
팀원 소개
필요성
간단한 앱 소개
2)
Problem
Solution
3)
차별성
추진방법 및 일정

이렇게 분배하는게 어떠신쥐

**Comment by LSA31** [comment]
팀원 소개
(역할 분담 설명 - 시간 남으면)
앱 이름 설명
필요성
앱 설명 (그래서 이런 걸 만들었다)
차별성
Ploblem
Solution

**Comment by KangJiUng** [comment]
팀 소개 -> 필요성 -> 문제
해결책 -> 앱 설명(차별성 포함)
팀원 역할 분배 -> 추진방법 및 일정

**Comment by LSA31** [comment]
앱 설명 내용입니다

폭식 예측 모델이 예측하여 그에 따른 결과를 토대로 사용자의 폭식 주기에 맞춰 사용자에게 push 알림(경고 알림)을 보낸다
사용자가 식단과 운동 루틴을 입력하면 발생할 효과를 예측하여 그에 따른 서비스를 제공
캐릭터를 육성하여 일정 레벨에 도달하면 그에 따른 보상이나 이벤트 응모 자격을 준다
사용자가 원하는 식재료를 입력 해당 식재료가 사용되는 다이어트 식단 레시피를 추천해준다
사용자가 섭취한 물, 영양제와 컨디션을 입력 받으면 캘린더에 감정 이모티콘으로 표시해준다
또 단순 월경 주기 확인용으로 월경 기간을 입력 받는다
사용자가 체중 변화를 입력하면 그래프화하여 보여준다

**Comment by KangJiUng** [comment]
추진 일정 공통에서 요구사항 정의, UI/UX 디자인, 기능정의 말고 하나 더 넣으면 좋을 것 같은데 뭐가 있을까요

**Comment by LSA31** [comment]
데이터 수집 어떠신가요?

**Comment by KangJiUng** [comment]
오우 좋습니다

**Comment by Hyunjiiing** [comment]
[팀소개]
[필요성] 다이어트는 평생 숙제. 다이어트 실패 요인 중 하나가 폭식. 이는 동기부여가 될 것. 우리의 서비스 소개 (뒷받침 : 기사 , 통계자료)
[문제] : 사용자의 폭식 타이밍을 예측하여 알림을 보내주고, 다이어트에 도움이 되는 서비스 만들기

**Comment by Hyunjiiing** [comment]
뒷받침 기사는 계속 찾아보는 중입니당

**Comment by KangJiUng** [comment]
문제를 쪼금만 더 구체화하면 좋을 것 같긴한데 그건 그냥 대본에서 해도 될 것 같군요

**Comment by Hyunjiiing** [comment]
넹 알것슴당

**Comment by Hyunjiiing** [comment]
[문제후보1] : 다이어트에 지속적인 동기를 부여할 수 있게 하는 서비스
[문제후보2] : 사용자의 폭식 타이밍을 예측하여 알림을 보내주고 지속적인 동기를 부여할 수 있게 하는 서비스
좀 구체화해봤는데 괜찮을까여?? 아니문 다른식으로 다시 생각해보겠습니당

**Comment by KangJiUng** [comment]
사용자의 폭식 타이밍을 예측하여 알림을 보내준다는 부분을 쪼금 구체화하는 게 좋을 것 같슴다 근데 이건 앱 설명에서도 나올 테니까 알아서 선택해서 하셔도 될 것 같아여 후보 1이랑 2 중에서는 1과 2를 섞는 게 좋아보여요

**Comment by KangJiUng** [comment]
메인화면 설계/개발/수정,보완
설정화면 설계/개발/수정,보완

**Comment by Hyunjiiing** [comment]
1주차 메인화면 설계 및 개발
2주차 설정화면 설계 및 개발
3주차 메인화면, 설정화면 수정 및 보완

**Comment by KangJiUng** [comment]
![image](https://user-images.githubusercontent.com/107825793/234270045-4c1775e0-d63c-4a3b-865a-a063865d0fe9.png)

개발 일정 수정하고 싶은 부분 있으시면 말씀해주세욤

**Comment by KangJiUng** [comment]
추진방법이랑 캐릭터 육성 기준? 어떻게 할근지도 좀 구체화 해야함니더

**Comment by KangJiUng** [comment]
<현지>
- 구글링을 통해 폭식 예측 관련 데이터들을 충분히 찾아보고 없으면 사용자들에게 일정 기간동안 입력받아 데이터를 확보한다.
- 예측 모델 결과(python)에서 firebase로 예측 결과를 전송하고 firebase에서 다시 flutter로 push 알람을 보낸다.
- flutter에서 라이브러리를 이용하여 앱 사용중과 사용안 할 때의 알람을 모두 구현한다.
- 데이터를 firebase(database)에 저장해둔다. 1년을 주기로 데이터들을 초기화한다.


<지웅>
- 신체 관련 자격증이 있거나 긴 기간 많은 사람에게 신뢰를 얻은 소스를 수집한다.
- 관련 api 가 있으면 사용한다.
- 데이터를 최대한 체계적으로 분류하고 Python 예측 알고리즘을 이용하여 매칭할 수 있도록 한다.
- 유사한 단어를 모두 학습시킨다.
- 3D나 채색이 있는 캐릭터보다 대충 그린듯 귀여운 그림체의 디자인을 이용한다.
변화를 시키되, 단계를 많이 두어 진화모습에 재미를 추가한다.
- 이전 상태의 데이터는 삭제하고 현재 상태를 저장하는 방식을 사용한다.


<승아>
- 다이어트 식단 레시피 데이터들을 수집 후 레시피에 있는 식재료들을 따로 추출하여 식재료에 해당하는 레시피들을 출력할 수 있도록 함
- SharePreferences 클래스가 제공하는 setter메서드(setInt, setBool, setString 등)를 사용하여 데이터를 저장하도록 함
- flutter에서 차트 패키지와 같은 것들을 활용하여 구글링을 통해 학습 후 그래프화 하도록 함

얘네 바탕으로 추진 방법 작성할 테니까 본인 부분에서 좀 더 구체적인 계획 있으면 꼭꼭 말씀해주세요

**Comment by KangJiUng** [comment]
아래는 중간 발표 피드백입니다.

- 프라블럼(풀고자하는 문제 자체)이랑 솔루션(인풋아웃풋)의 개념을 학기 초반에 말했었음 대부분 잘 잡아서 했는데 아닌 팀들은 보완해서 기말에 반영할 것. 우리 팀은 제대로 한 듯 하네요
- 데이터 수집 가능의 여부를 확인해야 함 긁어오는 것 자체에 민감한 곳도 있기 때문에 유의하기
- 발표 자료 만들 때 발표 기준에 따라 ppt 만들 것. 명확하게 점수 주기 위함임. 이것도 우리 팀은 제대로 함
- 예측인가 아닌가 애매하다면 지금이 라스트찬스 프로젝트 변경하려면 문의해서 바꾸기 우리는...안 애매하지?

다들 수고하셨씁니당
