### ISSUE TITLE
라이선스 설정하는 방법 제안

### ISSUE THREAD

**Issue by LSA31** [Hyunjiiing/OSS-TeamProject2#106]
라이선스 설정하는 방법을 아래 링크와 같은 방법으로 하는 거 어떨까요?

https://docs.github.com/ko/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by Hyunjiiing** [comment]
좋은생각인거 같아요! MIT 라이선스 내용으로 추가합시당
