### ISSUE TITLE
캐릭터 디자인 구현

### ISSUE THREAD

**Issue by KangJiUng** [Hyunjiiing/OSS-TeamProject2#11]
앱의 재미 요소로 들어갈 캐릭터의 디자인 구현에 대해 윤곽을 잡습니다

**Comment by KangJiUng** [comment]
일단 이슈 사항에서 캐릭터 디자인은 평면으로, 채색은 없이 대충 그린 듯한 디자인으로 하기로 했었는데용 제 바람은 이 평면으로 그린 그림을 3d로 움직이게 하는 겁니다...

**Comment by KangJiUng** [comment]
그냥 코딩으로 3d 를 구현하기는 힘드니까 아예 동영상을 넣는 것도 좋겠다는 의견이 있었어유

**Comment by KangJiUng** [comment]
캐릭터는 수집보다는 진화모습을 넣어서 다이어트 성공으로 같이 성장하는 맛을 넣도록 하겠숨니다

**Comment by KangJiUng** [comment]
그리고 캐릭터가 성장하는 요소는
1. 하루 칼로리 소모 기준을 초과한 만큼의 경험치 업
2. 오운완 포인트로 경험치 업
3. 전날과 비교해서 빠진 몸무게로 경험치 업

어떠신지?

**Comment by LSA31** [comment]
1, 2번은 앱 사용 동기가 돼서 좋은데, 3 번은 사용자가 레벨업을 하기 위해 무리하게 다이어트를 하면 위험할 것 같아서 빼는 게 좋을 것 같습니당!

**Comment by Hyunjiiing** [comment]
전날과 비교해서 몸무게 빼기는 힘드니까 전날대비 칼로리 소모량이 늘어나면 레벨업으로 하는게 어떠쉰지
4번 추가해서 몸무게는 한달 비교하는게 좋을듯용

**Comment by KangJiUng** [comment]
캐릭터가 성장하는 요소

1. 하루 칼로리 소모 기준을 초과한 만큼의 경험치 업
2. 전날 대비 칼로리 소모량 증가 시 경험치 업(증가 기준에 따라 포인트 고정)
3. 오운완 포인트로 경험치 업

으로 다시 정리했습니다 어떠신쥐 따봉 두 개 박히면 이걸로 할게요

**Comment by Hyunjiiing** [comment]
따봉티비

**Comment by KangJiUng** [comment]
[캐릭터 디자인 참고]
https://www.urbanbrush.net/downloads/%EC%97%AC%EC%9A%B0-%EC%9D%BC%EB%9F%AC%EC%8A%A4%ED%8A%B8-ai-%EB%AC%B4%EB%A3%8C%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C-free-fox-vector/
https://www.urbanbrush.net/?s=fox&post_type=download
https://kor.pngtree.com/freepng/cartoon-fox-vector_3318202.html
https://kor.pngtree.com/freepng/animals-fox-logo_4135359.html
https://kor.pngtree.com/freepng/animals-fox-logo_4135349.html
https://kor.pngtree.com/freepng/animals-fox-logo_4135335.html

**Comment by LSA31** [comment]
1,2,4번 좋은 것 같습니당

**Comment by Hyunjiiing** [comment]
저도 4번이 로고로 좋은거 같습니다!

**Comment by KangJiUng** [comment]
결정된 캐릭터 및 로고입니다
![IMG_1101](https://github.com/Hyunjiiing/OSS-TeamProject2/assets/107825793/ec39c480-05ee-4ccb-a6e6-a07db0b29e09)
![IMG_1104](https://github.com/Hyunjiiing/OSS-TeamProject2/assets/107825793/01e0cd0e-e712-4978-9570-481d6ccf8191)
