### ISSUE TITLE
앱 화면 UI 구상

### ISSUE THREAD

**Issue by LSA31** [Hyunjiiing/OSS-TeamProject2#12]
앱 화면마다 어떤 기능을 넣을지 어떻게 디자인 할 지 구상해봅시다

**Comment by Hyunjiiing** [comment]
메인 화면 - 귀여운 캐릭터, 식단 입력 
캘린더뷰 - 컨디션 기록(귀여운 요소),  
입력화면 - 식단, 체중, 물

push 알림 - 폭식 그만 알림

**Comment by KangJiUng** [comment]
일단 화면을 구분합시다 
메인화면
식단 입력화면
식단 및 운동 루틴 입력 화면
캘린더뷰
그래프화면
캐릭터 육성 화면
레시피 추천 화면
설정 화면

**Comment by LSA31** [comment]
캘린더뷰에 사용되는 기능은
물/영양제/컨디션/월경 입력 후 출력

**Comment by LSA31** [comment]
그래프 화면은 체중 변화 볼 수 있는 화면으로 만들면 될 것 같습니당

**Comment by LSA31** [comment]
월경 기간 입력 화면은 따로 제작하나요??

**Comment by Hyunjiiing** [comment]
그러네요

**Comment by KangJiUng** [comment]
입력 창으로 월경 시작, 끝만 입력하면 그 기간을  표시만 해주는 정도면 될 것 같으네여

**Comment by KangJiUng** [comment]
- HEX 코드가 #D7D8F1 이라면 #을 지우고 0xff를 앞에 붙여주세요

### 대표 색: #FF923F
### 흰.검.회는 플러터에서 제공하는 걸로 사용(ex: Colors.grey 사용)
테두리있으면 둥글게
참고 디자인(대표 색상을 포인트로 사용)
![KakaoTalk_20230428_185417992_01](https://user-images.githubusercontent.com/107825793/235117107-895ae3b3-1f08-4aed-b1aa-f16b395cc8d4.png)

**Comment by Hyunjiiing** [comment]
하단바 -> 메인 / 레시피 추천 / 예측 / 캘린더뷰

**Comment by KangJiUng** [comment]
아이콘은 apple 이모티콘 사용(https://velog.io/@gunwng123/Flutter-app-%EB%82%B4%EC%97%90%EC%84%9C-%EC%9D%B4%EB%AA%A8%EC%A7%80-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0)
하단바 사용(메인/예측/레시피추천/캘린더뷰), 우선은 모든 화면에 다 고정
 -> 예측은 폭식알림설정/식단운동효과예측으로 분류
설정은 톱니바퀴로
메인화면에 캐릭터 상태(버튼추가해서 상세화면), 식단입력버튼(아침, 점심, 저녁), 현재 체중(클릭하면 그래프)
상단은 주황색 물들이기(?)없이 그냥 흰색바탕

**Comment by LSA31** [comment]
메인 하단바(화면 넘어감) -> 메인 / 레시피 추천 / 예측 / 캘린더뷰 

메인 화면 구성요소 : 식단입력 / 체중 (누르면 그래프 볼수있게) / 캐릭터 (누르면 캐릭터 육성)

**Comment by Hyunjiiing** [comment]
![image](https://github.com/Hyunjiiing/OSS-TeamProject2/assets/107828202/adaec83e-e8cf-4421-b386-01b522608eb4)
main화면 최종 프로토타입입니당
