### ISSUE TITLE
Flutter SDK 버전 통일 제안

### ISSUE THREAD

**Issue by Hyunjiiing** [Hyunjiiing/OSS-TeamProject2#15]
서로 협업하게 되면 각자 Flutter SDK 버전이 달라서 생기는 오류가 많은데 통합하는게 어떨까요

**Comment by Hyunjiiing** [comment]
다들 SDK 버전 몇인가요 아마 flutter doctor로 알 수 있을듯 합니당

**Comment by KangJiUng** [comment]
저는 3.7.10 인듯요

**Comment by LSA31** [comment]
저는 3.7.12입니다

**Comment by Hyunjiiing** [comment]
저도 3.7.12 입니다 담에 회의할때 맞추죠!
