### ISSUE TITLE
유사 서비스 분석 및 앱 구상

### ISSUE THREAD

**Issue by Hyunjiiing** [Hyunjiiing/OSS-TeamProject2#2]
다이어트 관련 서비스들을 분석하고 차별성있는 앱을 구상합니다.

**Comment by KangJiUng** [comment]
우선 사용했던 다이어트 앱이 있다면 그걸 토대로 대화 나눠봅시당 우선 저는 '밀리그램'과 '인아웃'이라는 프로그램을 직접 사용해봤었는데요. 두 앱의 공통점은 입력한 식단의 칼로리를 계산해 주고 식단과 운동을 기록하며 커뮤니티도 형성되어 있었어요.

**Comment by KangJiUng** [comment]
두 앱이 가지는 차별성이라면, 이모티콘과 한 줄정도의 글로 일기장을 작성하거나 스마트워치와 운동/걸음수/신체 등의 정보가 연동되는 기능, 캘린더뷰, 식단 점수 평균, 기간별 통계 그래프정도가 있는 것 같아요.

**Comment by KangJiUng** [comment]
그리고 어제 실제로 다이어트를 위해 앱을 찾아보다가 '간단'이라는 간헐적 단식을 위한 다이어트 앱을 발견했는데요. 저희가 생각했던 폭식 타이밍을 분석해 알림을 보내는 것과 비슷한 기능이 있었어요. 단식 요일과 시간대를 설정하면, 시작과 종료시간에 알림을 보내고 단식을 잘 지켰는지에 대한 여부 또한 물어봐주는 기능도 있었습니다. 그런데 저희가 구상했던 기능이 완전히 그대로 들어간 앱은 발견하지 못했어요!

**Comment by Hyunjiiing** [comment]
저는 다이어트신이라는 어플을 사용해봤었는데 목표 몸무게와 원하는 한달 감량 몸무게를 입력하면 하루에 먹어야하는 칼로리를 계산해주어 식단을 입력했을때 적정량을 알 수 있게 되어 좋았습니다. 다이어트 플랜을 잘 짜주는 어플임이 차별성이라고 느꼈어요. 운동 입력시 예상되는 칼로리량, 위에 지웅님이 말씀하신 통계 그래프 기능도 있었습니다.

**Comment by Hyunjiiing** [comment]
저도 이 앱에서 포기순간을 '예측'하는 기능은 발견하지 못했습니다.

**Comment by KangJiUng** [comment]
그럼 저희가 구상했던 기능인 폭식 타이밍 분석 및 예측, 경고 알림 제공이 첫 번째 차별성이 될 수 있겠네요. 그리고 입력한 식단과 운동 루틴을 입력하면 그 효과를 예측해주는 서비스 또한 목표 몸무게와 원하는 감량 몸무게 입력 시 하루에 먹어야하는 칼로리를 계산해주는 것과는 다르니 차별성이 있다고 볼 수 있겠어요!

**Comment by KangJiUng** [comment]
다이어트 앱에 필수적인 기능을 구상하기 전, 혹시 또 다른 부분에서 줄 수 있는 차별성에 대한 의견이 있을까요? 저는 일단 디자인적인 부분에서 다른 앱과는 다른 차별성을 주면 좋을 것 같아요.

**Comment by Hyunjiiing** [comment]
좋습니다! 저는 다이어트 앱 특성상 지속적인 참여가 제일 중요하니까 그런것들을 유발하는 요소들이 있으면 좋겠습니다.

**Comment by Hyunjiiing** [comment]
예를 들어 참여하면 포인트가 쌓이고 그 포인트로 보상을 받을 수 있는 제도가 포함되면 좋을거 같아요!

**Comment by KangJiUng** [comment]
포인트를 통한 보상 제도 좋은 것 같습니다! 그럼 디자인과 지속적인 참여 유발에 대한 구상을 정확히 해봅시당 우선 제가 다이어트 앱을 사용해보고 느낀 건 디자인이 심플하고 둥글거나, 귀여운 요소가 포함되어 있으면 사용할 맛이 더 나는 것 같더군요ㅎ  개인적으로 저는 심플쪽으로 갔으면 좋겠습니다. 뒤늦게 생각난 앱이 하나가 있는데, '나다'라는 앱이 다이어트 기록앱인데, 구성이 심플해서 디자인이 제일 마음에 들었어요.

**Comment by Hyunjiiing** [comment]
저는 디자인적인 부분에서는 앱을 처음 실행하자 마자 캘린더가 보이는 것이 좋은거 같아요. 다른 앱들중에는 커뮤니티같은 다른 부분이 첫 시작 화면인 경우가 있었는데 식단을 입력하기에 좀 번거롭다는 느낌을 받았었습니다. 아니면 오늘 하루에 식단, 운동 입력 부분이 시작화면이 되는것도 좋을거 같습니다.

**Comment by KangJiUng** [comment]
그리고 방금 다이어트 앱을 보다보니 발견했는데, '지니어트'라는 앱이 매일 다이어트 기록을 하면 돈처럼 쓸 수 있는 캐시를 주는 앱이더라구요. 캐시를 주는 기능을 자세히 계획하고 구현할 때는 이 앱을 직접 보고 차별성을 찾아야 할 것 같아요.

**Comment by Hyunjiiing** [comment]
다이어트 앱의 활성 사용자수가 여성이 더 높은것을 고려하였을때 귀여운 요소를 갖는것이 좋은 의견인거 같습니다! 귀여운것 관련하여 다이어트가 진행됨에 따라 귀여운 캐릭터가 성장되는 요소를 추가하는것도 좋을거같아요. 지속적인 참여 유발도 될거같습니다.

**Comment by Hyunjiiing** [comment]
오.. 저희는 사용자가 포인트를 돈처럼 사용할수 있게 할만큼의 돈이 없으니 고민해봐야겠네요

**Comment by KangJiUng** [comment]
캐릭터가 성장되는 요소 좋네요ㅋㅋ 캐릭터가 일정 레벨까지 도달하면 더 큰 보상이나 이벤트에 응모할 자격을 주는 것도 좋을 것 같아요. 아 그리고 우리 앱이 다이어리처럼 기록이 주가 되는 앱이 될 건지, 다이어트 성공에 도움이 될 앱이 될 건지도 확실히 정하면 좋을 것 같아요!

**Comment by Hyunjiiing** [comment]
저는 예측하는 부분이 지속적인 다이어트를 이끄는거라고 생각해서 성공에 도움을 주는게 주가된다고 생각해요. 근데 다이어트는 평생하는거기도 하니까..

**Comment by Hyunjiiing** [comment]
지금까지 말한것들을 토대로 필요한 페이지들을 구상해보고 구상하면서 더 추가할까요??

**Comment by KangJiUng** [comment]
그래요 그럼 일단 성공에 도움이 되고자함을 목적으로 잡고 구상 시작해봅시다 그리고 자신이 가지고 있는 식재료를 입력하면 유튜브 같은 곳에 나와있는 다이어트 식단을 참고해서 제공해주는 기능도 있으면 좋을 것 같아요

**Comment by Hyunjiiing** [comment]
오 좋습니다!

**Comment by Hyunjiiing** [comment]
각자 메인페이지를 간단하게 구상해보고 올려볼까요??

**Comment by KangJiUng** [comment]
네 좋습니당

**Comment by Hyunjiiing** [comment]
![image](https://user-images.githubusercontent.com/107828202/229057390-636dd9fb-a137-498b-af7f-8a7c79a0059d.png)

이런식으로 캐릭터와 식단입력을 주로 하고 돋보기 버튼을 누르면 식단 입력 페이지로 넘어가게 만들면 좋을거같아요!

**Comment by Hyunjiiing** [comment]
입력하는거니까 돋보기 말고 "입력"이 더 좋을거 같네용 아니면 밥을 주는 컨셉이니까 "밥주기"라던지??

**Comment by KangJiUng** [comment]
![image](https://user-images.githubusercontent.com/107825793/229061309-8feca685-cb42-4d51-8ef4-d284b0a6f75a.png)

**Comment by Hyunjiiing** [comment]
오!!! 너무 좋아요

**Comment by KangJiUng** [comment]
일단 저희가 이때까지 넣으려고 구상한 기능이
- 폭식 타이밍 분석 및 예측 후 경고 알림 보내기
- 식단과 운동 루틴 입력하면 발생할 효과 예측 서비스 제공
- 캐릭터 육성
- 식재료 입력 시 다이어트 식단 레시피 추천
이죠?? 그 외에 다른 다이어트 앱도 사용하는 기능은 뭘 넣으면 좋을까요?? 우선 아점저 사진+식단 입력, 운동 시간 입력정도가 제가 메인페이지에 넣은 기능이에요.

**Comment by Hyunjiiing** [comment]
지웅님의 아침, 점심, 저녁 버튼이 딱 보이는거랑 하단바랑 캐릭터 키운 날짜를 보여주는게 좋은거 같습니다!!

**Comment by Hyunjiiing** [comment]
식단 입력을 했는데 사진을 넣어야하는 이유가 있을까요?? 나중에 볼 수 있도록 기록용으로 넣는거죠?? 사진을 저장하다보면 앱 자체의 용량이 커져서 저희 실력상 렉이 걸릴까봐 ㄷ..두렵네요

**Comment by KangJiUng** [comment]
그럼 그 부분은 실제 개발에 들어가서 문제가 생긴다면 그냥 식단만 기록하는 걸로 수정하도록 합시당

**Comment by Hyunjiiing** [comment]
넹 나중에 개발하면서 한달 단위로 초기화 한다던지 DB를 사용해보는것도 좋을거 같습니다!

**Comment by KangJiUng** [comment]
물/컨디션/영양제 기록, 체중 또는 칼로리 그래프, 캘린더뷰정도가 대부분의 다이어트 앱들이 가지고 있는 기능인 것 같아요. 이것들을 혹시 다 넣을 수 있을까요? 아니면 캘린더뷰만 제외한 기능들이요!

**Comment by Hyunjiiing** [comment]
그정도는 다 넣을 수 있을거 같아용. 대부분 기록하는게 많은걸로 봐서 DB 사용은 필수적일거 같아요. DB로는 일정 사용량까지는 무료이고 사용하기 쉬운 firebase가 좋을거 같습니다!

**Comment by Hyunjiiing** [comment]
여성 사용자들에겐 월경도 다이어트에 중요한 영향을 미치니까 월경기간도 기록하고 예측시에 그런 요소들을 고려하는게 좋을거같습니다!

**Comment by KangJiUng** [comment]
넹 좋아용 안 그래도 저희 폭식 방지 알림이 월경 앱과도 비슷하다는 생각을 했었어요! 그럼 이제 역할 분배를 조금 해보면 좋을 것 같아용 기능적으로 나누어야 할지 아니면 백엔드 프론트엔드로 나누어야 할지 모르겠네욥

**Comment by Hyunjiiing** [comment]
저희는 아직 둘 중 하나를 전문적으로 할 수 있는 능력이 없고 배우는 단계니까 기능적으로 나누고 막히는 부분이 생기면 서로 도와주는 편이 좋을거 같아요!

**Comment by KangJiUng** [comment]
좋습니다!! 그럼 

- 폭식 타이밍 분석 및 예측 후 경고 알림 보내기
- 식단과 운동 루틴 입력하면 발생할 효과 예측 서비스 제공
- 캐릭터 육성
- 식재료 입력 시 다이어트 식단 레시피 추천
- 식단 및 운동량 입력
- 물/컨디션/영양제/월경 기록
- 체중 또는 칼로리 그래프
- 캘린더뷰

이렇게가 기능 정리 맞을까요?

**Comment by Hyunjiiing** [comment]
- 폭식 타이밍 분석 및 예측 
- 폭식 타이밍에 경고 알림 보내기
- 식단과 운동 루틴 입력하면 발생할 효과 예측
- 식단 운동 루틴 예측 결과 서비스 제공
- 캐릭터 육성
- 식재료 입력 시 다이어트 식단 레시피 추천
- 물/컨디션/영양제/월경 기록
- 체중 또는 칼로리 그래프
- 캘린더뷰

**Comment by Hyunjiiing** [comment]
뭔가 예측하는 기능이 제일 어려울거 같아서 두개로 나누는거 어떠세용??

**Comment by Hyunjiiing** [comment]
푸시 알람보내는것도 저한테는 좀 어려운 작업이었어 가지구용..

**Comment by KangJiUng** [comment]
괜찮은 것 같아요 그럼 비교적 쉬운 기능은 각종 기록, 그래프, 레시피 추천 정도가 될까요?

**Comment by KangJiUng** [comment]
저희 역할 분배 이슈 나눕시다

**Comment by Hyunjiiing** [comment]
넹!!

**Comment by Hyunjiiing** [comment]
고럼 새로운 이슈로 넘어가는건가용

**Comment by KangJiUng** [comment]
수고하셨씨용..~
