### ISSUE TITLE
API 참고 링크

### ISSUE THREAD

**Issue by KangJiUng** [Hyunjiiing/OSS-TeamProject2#20]
API 관련 참고 링크를 기록합니다.

**Comment by KangJiUng** [comment]
[식단]
http://api.nongsaro.go.kr/sample/ajax/recomendDiet/recomendDietList.html
https://github.com/huusz/Da-Da
https://www.upstage.ai/blog/insight/askup-use-case-health

[운동]
https://5weeksdiary.com/entry/AI-%ED%97%AC%EC%8A%A4%EC%BC%80%EC%96%B4-%EC%96%B4%ED%94%8C-%EA%B0%9C%EB%B0%9C-3-%EC%96%B4%ED%94%8C%EB%A6%AC%EC%BC%80%EC%9D%B4%EC%85%98-%EC%A0%9C%EC%9E%91-%EA%B3%84%ED%9A%8D-%EB%B0%8F-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%88%98%EC%A7%91
https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE06242475
https://m.dietshin.com/mweb_v4/newcommunity/bbs_view_from_log.asp?idx=5163959
https://koreascience.kr/article/JAKO201022442398235.pdf
https://koreascience.kr/article/CFKO200932963976785.pdf

**Comment by KangJiUng** [comment]
[캐릭터육성]
https://docs.tentuplay.io/unity/ko/latest/api-reference/unity/tpstashevent/tpstashevent.levelupcharacter/
https://www.acmicpc.net/problem/20211
https://ansohxxn.github.io/unity%20lesson%202/ch13-10/
https://velog.io/@starkshn/%EB%A0%88%EB%B2%A8%EC%97%85#
https://makerejoicegames.tistory.com/53
https://discordbot.tistory.com/242
https://pypi.org/project/mee6-py-api/
https://github.com/Miic/Mee6-API-Wrapper-for-Java

**Comment by KangJiUng** [comment]
https://www.foodsafetykorea.go.kr/api/newUserApiAplcDtl.do?menu_grp=MENU_GRP32&menu_no=3995
https://www.foodsafetykorea.go.kr/api/howToUseApi.do

**Comment by KangJiUng** [comment]
https://www.omnicalculator.com/health/bmr-harris-benedict-equation
https://github.com/isfonzar/tdee-calculator

**Comment by KangJiUng** [comment]
https://rapidapi.com/malaaddincelik/api/fitness-calculator/details

**Comment by KangJiUng** [comment]
[사용법]
https://cholol.tistory.com/568

**Comment by LSA31** [comment]
https://www.foodsafetykorea.go.kr/api/newDatasetDetail.do

식단 레시피

**Comment by KangJiUng** [comment]
https://sidongmen.tistory.com/11

**Comment by KangJiUng** [comment]
[식단 칼로리 최종 api]
https://www.data.go.kr/data/15047698/fileData.do
