### ISSUE TITLE
[긴급] 프로젝트 수정

### ISSUE THREAD

**Issue by LSA31** [Hyunjiiing/OSS-TeamProject2#21]
프로젝트를 수정해봅시다.

**Comment by KangJiUng** [comment]
일단 기능 몇 개 삭제하고 디자인을 나눠서 하지 말고 한 명이 도맡아서 하는 게 나을 듯 싶습니다(+팀원 돕기) 깃헙 파일 올려둔 것도 분류를 좀 해야할 것 같고욥

**Comment by Hyunjiiing** [comment]
오 인정 디자인 정말 인정합니다

**Comment by LSA31** [comment]
오 한 명이 하는 거 좋은 것 같습니다

**Comment by Hyunjiiing** [comment]
기능 삭제하면 완성도 점수 까이지 않을까요

**Comment by LSA31** [comment]
그럼 디자인 도맡은 사람은 개발은 안하고 UI?만 디자인 하는 건가요?

**Comment by Hyunjiiing** [comment]
음 디자인 코드 짜는거까지 일듯요??

**Comment by KangJiUng** [comment]
디자인+팀원개발돕기

**Comment by Hyunjiiing** [comment]
그리고 기능이랑 디자인 코드 융합하는것도 해야할듯

**Comment by LSA31** [comment]
아 완성도는 까일 것 같긴한데..

**Comment by KangJiUng** [comment]
근데 이미 너무 미뤄버려서 제가 루틴 입력했을 때 효과 나오게 하는 걸 구현을 못하지 싶은데

**Comment by Hyunjiiing** [comment]
아니믄 좀 현실적으로 기간내에 하기 어려운 기능들 일단 빼지말고 저한테 몰아주시면 최대한 해볼게요

**Comment by KangJiUng** [comment]
음... 기능을 안 뺄 거면 일단 최대한 해보긴 할 건데... 몰아달라는 거는 그럼 지금 몰아달라는거죠

**Comment by Hyunjiiing** [comment]
그렇습니다요 아예 빼는게 나을까요??

**Comment by LSA31** [comment]
아니면 몰아드리고 현지님 못 하실 것 같으면 그때 아예 빼는 건 어떤가요?!

**Comment by Hyunjiiing** [comment]
저는 좋아요

**Comment by KangJiUng** [comment]
제가 봤을 땐 다른 기능들은 다 남은 기간 안에 몸 갈면 가능할 것 같은데 내가 맡은 예측이 제일 문젠 것 같아유 캐릭터 육성 부분이 생각보다 해야하는 게 뭐가 많을 것 같아서... 아니면 제가 캐릭터 육성이랑 식단 기록 부분 하는 동안 현지가 루틴 예측까지 하고 있으면 필요할 때 도움 드릴게여 어떠삼

**Comment by LSA31** [comment]
근데 저번 발표때 피드백 받은 걸 토대로 수정했다고 치면 
완성도에서 감점 없지 않을까요???

**Comment by Hyunjiiing** [comment]
좋아용

**Comment by Hyunjiiing** [comment]
피드백 받은게 뺄만한 고런게 있었나요?? 그럼 이득인데

**Comment by LSA31** [comment]
뭐 딱히 없긴한데 저번 발표때 다른 팀이나 피드백 받은 걸로 수정할 수도 있는 거 아닐까????라는 말입니댜

**Comment by KangJiUng** [comment]
아항... 근데 그게 프로젝트를 전반적으로 바꿀 거면 교수님한테 공유하라고 하셨어서 약간 다를지도..?

**Comment by LSA31** [comment]
아악 이런..

**Comment by KangJiUng** [comment]
근데 솔직히 우리가 미는 예측 부분이 그 폭식 방지 알림이 제일 큰 거라서 다른 팀이 갑자기 한 달만에 완성도 지리는 프로그램들을 만들어 오는 게 아니면 심각하게 까일 것 같진 않아유 그래도 일단 기능은 그대로 하고 다시 역할을 배분할까요?

**Comment by KangJiUng** [comment]
한 명이 디자인을 도맡아서 하면 기능을 그대로 하는 게 조금 벅찰 것 같긴 한데

**Comment by LSA31** [comment]
넵넵

**Comment by Hyunjiiing** [comment]
넹 그럽시다 기간이 그래도 있으니까 최소한으로 까이는게 나을듯

**Comment by LSA31** [comment]
자기가 맡은 역할 다 보내볼까여

**Comment by LSA31** [comment]
체중 변화 그래프
캘린더뷰 (물/컨디션/영양제/월경 기록)
식재료 입력 시 다이어트 식단 레시피 공유

**Comment by Hyunjiiing** [comment]
![image](https://github.com/Hyunjiiing/OSS-TeamProject2/assets/107828202/352ea7ac-3d9a-44fc-8229-1b5a5d66fae3)
요거 보고 재구성하면 좋을 거 같아요

**Comment by KangJiUng** [comment]
일단 디자인은 누가 맡을까요

**Comment by LSA31** [comment]
근데 한 명이 디자인 도맡아하면 나머지 팀원들이 맡은 기능이 넘 많아질 것 같은데 괜찮을까여???

**Comment by KangJiUng** [comment]
디자인을 3주 내내 할 것 같진 않아서... 디자인도 제 생각엔 몇 개 맡는 게 좋을 것 같은데 힘들려나요

**Comment by LSA31** [comment]
그렇게 합시당

**Comment by Hyunjiiing** [comment]
음 근데 디자인이 앱  UI 전체 코드 짜는거죠

**Comment by KangJiUng** [comment]
넴 그렇게 될 것 같아용

**Comment by LSA31** [comment]
저희 기능 배분 먼저하고 누가 맡을 지 정하는 건 어떤가용

**Comment by Hyunjiiing** [comment]
설정 화면이랑 메인화면 식단 입력화면 이런거 다니까 처음하면 2주 안에는 이것도 벅찰 거 같기는 한데

**Comment by Hyunjiiing** [comment]
좋습니다

**Comment by LSA31** [comment]
그것도 맞아요...

**Comment by LSA31** [comment]
디자인 한 명이 도맡아 하는 게 다른 팀원이 기능 구현해놓으면 그걸 전체 디자인에 맞추려고 수정하는 건가용?

**Comment by Hyunjiiing** [comment]
다른 기능들이 난이도가 높기도 하고 디자인 한명만 하는게 서로 맞추는거보다 효율적이어서 수정하는거 같은데

**Comment by KangJiUng** [comment]
음.. 따로 맡으니까 디자인 통합이 안되는 게 제일 커요 이거 스타일이 다 달라서 맞추는 것만 한 세월일 것 같아서

**Comment by Hyunjiiing** [comment]
일단 저는 
- 폭식 예측 및 푸시알람 전송
- 운동 입력시 예상 칼로리량 예측
요거랑 더 맡을거 있을까요??

**Comment by LSA31** [comment]
메인 화면이랑 설정 화면??

**Comment by KangJiUng** [comment]
그럼 그냥 기능을 줄여야 할 것 같은데... 피그마 inspect 창도 찾아보니까 아예 처음부터 끝까지 쭉 해준다기보다 각 객체마다 여백, 폰트, 크기 뭐 이런 거 정도만 개발자들이 편리하게 해주는 정도인 것 같네유

**Comment by KangJiUng** [comment]
> 일단 저는
> 
> * 폭식 예측 및 푸시알람 전송
> * 운동 입력시 예상 칼로리량 예측
>   요거랑 더 맡을거 있을까요??

이거 운동 입력 시 예상 칼로리량 예측이 아니고 성별, 나이, 식단이랑 운동 루틴, 기초대사량(선택), 기간(선택) 등등 입력했을 때 반영해서 다이어트 결과 예측 해주는 거예욥 이런 거까지 있어야 예측도 그렇고 더 정확한 결과가 나오는 것 같더라고요

**Comment by KangJiUng** [comment]
피그마도 따로 강좌가 있을 만큼 생각보다 알아야 할 게 많아요..

**Comment by Hyunjiiing** [comment]
그냥 피그마 사용하지 말고 디자인 좀 투박하더라도 플러터만 하는게 나은거 같아요

**Comment by KangJiUng** [comment]
그리고 저희 데이터베이스도 써야 할 것 같아요 생각해보니 저번 스룸에서 회의했을 때 체중 그래프 월경 기간 이런 거 공유해서 쓸 것도 꽤 있었어요

**Comment by KangJiUng** [comment]
> 그냥 피그마 사용하지 말고 디자인 좀 투박하더라도 플러터만 하는게 나은거 같아요

근데 이게 제 입장에선 플러터도 구글링하면서 배워야 하는 거라 이러나 저러나 시간이 좀 걸려서 그냥 ui 배치 하는 거라도 쉬우려고 피그마 선택했던 건데 해 본 입장으로서 안 쓰는 게 더 나을 것 같으면 그냥 플러터로 ㄱㄱ 해요

**Comment by LSA31** [comment]
공유 복잡하다고 안하기로 하지 않았나여?!

**Comment by LSA31** [comment]
피그마 사용은 두 분 의견을 따르겠습니당

**Comment by KangJiUng** [comment]
저번에 회의할 때 그랬나욤?

**Comment by LSA31** [comment]
넹 그때 현지가 복잡하다고 했던 것 같은데 아닌가욥

**Comment by Hyunjiiing** [comment]
안쓰는게 더 나을거 같습니닷

**Comment by Hyunjiiing** [comment]
피그마 ㅇㅇㅇㅇ

**Comment by KangJiUng** [comment]
그냥 전화 ㄱㄱ 하죠 너무 딜레이되는데

**Comment by Hyunjiiing** [comment]
음 아니면 제가 전체 앱 UI랑 예측 두개랑 푸시알림 하는거 최대한 빨리 해볼테니까

**Comment by Hyunjiiing** [comment]
ㅇㅈ합니다

**Comment by KangJiUng** [comment]
https://cpcp127.tistory.com/21

**Comment by KangJiUng** [comment]
- 캘린더뷰: 각종 기능 -> 날짜 클릭 시 메모 기록 기능으로 변경

**Comment by KangJiUng** [comment]
월요일까지 각자 개발 부분 최대한 많이 할것

**Comment by KangJiUng** [comment]
파이어베이스는 쓰지말고 그냥 api랑 https://velog.io/@stone1098/flutter-SharedPreferences%EC%9C%BC%EB%A1%9C-%EB%A1%9C%EC%BB%AC%EC%97%90-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%A0%80%EC%9E%A5%ED%95%98%EA%B8%B0 이거 참고해서 합시다 파이팅이용

**Comment by Hyunjiiing** [comment]
프로젝트를 더 시도해 본 결과 가능하다고 판단되어 수정하지 않는 방향으로 진행하였습니다.
