### ISSUE TITLE
프로젝트 역할 분배

### ISSUE THREAD

**Issue by KangJiUng** [Hyunjiiing/OSS-TeamProject2#3]
프로젝트의 기능적 요소를 기준으로 역할을 분배합니다.

**Comment by KangJiUng** [comment]
- 폭식 타이밍 분석 및 예측
- 폭식 타이밍에 경고 알림 보내기
- 식단과 운동 루틴 입력하면 발생할 효과 예측
- 식단 운동 루틴 예측 결과 서비스 제공
- 캐릭터 육성
- 식재료 입력 시 다이어트 식단 레시피 추천
- 물/컨디션/영양제/월경 기록
- 체중 또는 칼로리 그래프
- 캘린더뷰

**Comment by KangJiUng** [comment]
앞 5개가 비교적 어렵고 나머지 4개가 비교적 간편하다고 보면 될까용

**Comment by Hyunjiiing** [comment]
음.. 정확한건진 모르겠으나 저의 경험에 의해서 그렇다고 볼 수 있습니닷

**Comment by Hyunjiiing** [comment]
제 생각에는 
1. 예측1 + 서비스1
2. 예측2 + 서비스2
3. 나머지 기능들싹다
이런식으로 역할분배 하는것도 좋을거 같습니다!

**Comment by Hyunjiiing** [comment]
그리고 1번 2번 사람이 빨리 끝내면 3번 사람들한테 더 역할 부여받는식으로?? 해도 좋을거같아용

**Comment by KangJiUng** [comment]
그러면 나눠서

- 폭식 타이밍 분석 및 예측, 월경 기록
- 폭식 타이밍에 경고 알림 보내기
---------------------------------------------------
- 식단과 운동 루틴 입력하면 발생할 효과 예측
- 식단 운동 루틴 예측 결과 서비스 제공
- 캐릭터 육성
---------------------------------------------------
- 식재료 입력 시 다이어트 식단 레시피 추천
- 물/컨디션/영양제 기록
- 체중 또는 칼로리 그래프, 캘린더뷰

이렇게는 어떨까요? 월경이 폭식 타이밍 분석이랑 제법 비슷한 알고리즘을 가지고 있을 것 같아서 하는 김에 같이 하면 이해도가 빠를 수 있을 것 같고 예측 결과 서비스 제공은 취합해서 보여주는 게 주된 알고리즘 같아서 캐릭터 육성까지 넣었어요. 그리고 말씀하신 대로 누구든지 먼저 끝난다면 도움이 필요한 팀원을 도와주면 될 것 같네요!

**Comment by Hyunjiiing** [comment]
오 좋습니다!!! 깔꼼 그 자체

**Comment by KangJiUng** [comment]
그럼 정리 순서대로 현지-지웅-승아로 역할 분배 마무리하겠습니다! 수고하셨습니닷

**Comment by Hyunjiiing** [comment]
넹 감사합니당~~

**Comment by Hyunjiiing** [comment]
바바잉
