### ISSUE TITLE
명명 규칙 결정

### ISSUE THREAD

**Issue by LSA31** [Hyunjiiing/OSS-TeamProject2#4]
브랜치 명과 규칙 결정해봅시당

**Comment by Hyunjiiing** [comment]
넹구리구리

**Comment by KangJiUng** [comment]
일단 브랜치명은 Feature_(임의)로 고정이 되어야 하니까 각자를 대표하는 숫자나 영어를 하나 정하면 좋을 것 같아요

**Comment by Hyunjiiing** [comment]
https://velog.io/@kim-jaemin420/Git-branch-naming
요런 사이트를 참고해서 정해도 좋을거 같아용

**Comment by Hyunjiiing** [comment]
넹 엄 저는 영어로 하면 O 숫자로 하면 5 할래요

**Comment by LSA31** [comment]
저는 그럼 영어면 E 숫자면 2 하겠습니다~~

**Comment by Hyunjiiing** [comment]
오!! 이런 딱딱 맞는일이

**Comment by KangJiUng** [comment]
영어로 합시다!!ㅋㅋ 전 J요 사용한다면 

- Feature_J_Data 
- Feature_J-Data
- Feature_(J)Data
- Feature_J/Data

중에 어떤 게 좋을까요?? 아니면 다른 의견 있으시면 말씀해주세용

**Comment by LSA31** [comment]
첫번째가 맘에 들어요!

**Comment by Hyunjiiing** [comment]
오 1번 혹은 3번 강추드려요

**Comment by KangJiUng** [comment]
그러믄 1번으로 고고합시다

**Comment by LSA31** [comment]
넹넹

**Comment by Hyunjiiing** [comment]
대문자 소문자 중에 소문자로 하면 될까여

**Comment by KangJiUng** [comment]
아니요 대문자요^.^

**Comment by Hyunjiiing** [comment]
넹

**Comment by KangJiUng** [comment]
> 영어로 합시다!!ㅋㅋ 전 J요 사용한다면
> 
> * Feature_J_Data
> * Feature_J-Data
> * Feature_(J)Data
> * Feature_J/Data
> 
> 중에 어떤 게 좋을까요?? 아니면 다른 의견 있으시면 말씀해주세용

### Feature_J_Data

**Comment by Hyunjiiing** [comment]
뒤에 Data이 부분은 그냥 알아서 정하면 될까요

**Comment by KangJiUng** [comment]
그 외에 커밋 특징에 따라서도 정하면 좋을 것 같은데 혹시 의견 있으신 분!!

**Comment by LSA31** [comment]
좋아요!

**Comment by Hyunjiiing** [comment]
엄 
Fix -> 기존의 코드를 수정했을때
Make -> 새로운 코드를 만들었을때
이거밖에 생각이 안나요

**Comment by Hyunjiiing** [comment]
feat : 새로운 기능에 대한 커밋
fix : build 빌드 관련 파일 수정에 대한 커밋
build : 빌드 관련 파일 수정에 대한 커밋
chore : 그 외 자잘한 수정에 대한 커밋(rlxk qusrud)
ci : CI 관련 설정 수정에 대한 커밋
docs : 문서 수정에 대한 커밋
style : 코드 스타일 혹은 포맷 등에 관한 커밋
refactor : 코드 리팩토링에 대한 커밋
test : 테스트 코드 수정에 대한 커밋

**Comment by Hyunjiiing** [comment]
인터넷에서 퍼왔어요

**Comment by LSA31** [comment]
일단 저거대로 한 다음에 더 필요한 부분있을 때마다 추가하는 건 어떨까용?

**Comment by Hyunjiiing** [comment]
오 그것도 좋을듯여

**Comment by Hyunjiiing** [comment]
feat : 새로운 기능에 대한 커밋
fix : build 빌드 관련 파일 수정에 대한 커밋
build : 빌드 관련 파일 수정에 대한 커밋
chore : 그 외 자잘한 수정에 대한 커밋(rlxk qusrud)
docs : 문서 수정에 대한 커밋
style : 코드 스타일 혹은 포맷 등에 관한 커밋
refactor : 코드 리팩토링에 대한 커밋
test : 테스트 코드 수정에 대한 커밋

저는 CI만 제외하고 다 사용하면 좋을거같아요

**Comment by KangJiUng** [comment]
### feat : 새로운 기능에 대한 커밋
### fix : 코드 수정에 대한 커밋(버그 피드백에 관한 거면 bug fix 이런 식으로 사용)
### test : 테스트 코드 수정에 대한 커밋
### docs : 문서 수정에 대한 커밋
### refactor : 코드 리팩토링에 대한 커밋
### style : 코드 스타일 혹은 포맷, ui 등에 관한 커밋
### chore : 그 외 자잘한 수정에 대한 커밋(기타 변경)

외에 추가 하는 걸로!
