### ISSUE TITLE
앱 이름 정하기

### ISSUE THREAD

**Issue by Hyunjiiing** [Hyunjiiing/OSS-TeamProject2#5]

**Comment by Hyunjiiing** [comment]
1. 살.zip
2. 빼면돼지
아재개그 그자체

**Comment by LSA31** [comment]
다가능 (다이어트 가능..)

**Comment by Hyunjiiing** [comment]
최대 3단어가 좋다고 하긴하네용

**Comment by Hyunjiiing** [comment]
올

**Comment by Hyunjiiing** [comment]
다가능 좋은데요

**Comment by Hyunjiiing** [comment]
앱 광고에
다이어트하면 다~ 가능해지니까! 하는 상상함

**Comment by LSA31** [comment]
따당따당 (다이어트하는 당신......)

**Comment by Hyunjiiing** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ귀여워여

**Comment by KangJiUng** [comment]
1. 이팅어웨이(eating away 먹는거 꺼져의 의미긴 한데 미치게 만든다, 잠식시킨다는 뜻이 있네여;;;쩝)
2. 칼로너스(kcalories minus)
3. 슬리머트(slimart / slim diet를 합쳐말함, 스마트하게 살빼자!^^)
4. 바디쏙 (바디가 쏘옥ㅋ)
5. 폭스(폭식스탑 줄임)

**Comment by Hyunjiiing** [comment]
ㄷㄷㄷㄷㄷ바디쏙 좋아요

**Comment by Hyunjiiing** [comment]
폭스보다 폭스탑이 더 좋은느낌

**Comment by KangJiUng** [comment]
올 굿굿

**Comment by LSA31** [comment]
폭스 조아용

**Comment by LSA31** [comment]
캐릭터 ui도 여우로 하면 될 것 같은 ㅎㅎㅎ

**Comment by KangJiUng** [comment]
여우처럼 늘씬해지는 것이쥐

**Comment by Hyunjiiing** [comment]
ㅇㅈㅇㅈ

**Comment by Hyunjiiing** [comment]
여우 플러팅 팍팍

**Comment by LSA31** [comment]
후보 나온 것 중에 정할까여???

**Comment by KangJiUng** [comment]
네네넵

**Comment by Hyunjiiing** [comment]
제 마음속 순위
1. 폭스 혹은 폭스탑
2. 다가능
3. 바디쏙

**Comment by LSA31** [comment]
폭스
다가능 
뺴면돼지

**Comment by LSA31** [comment]
전 이 세가지가 귀여워서 좋은 것 같으요

**Comment by Hyunjiiing** [comment]
![image](https://user-images.githubusercontent.com/107828202/230600007-3fc86825-a465-41bc-9e18-0a1327977949.png)
흐으음 너무 아이디어가 다 좋은디 난 결정 모대

**Comment by LSA31** [comment]
저희 앱은 다른 앱들이랑 비교했을 때 폭식을 예측하는 부분이 가장 큰 장점이니까 폭스가 가장 맘에 듭니다여

**Comment by Hyunjiiing** [comment]
저도 똑같은 생각22

**Comment by KangJiUng** [comment]
흠 그러면 폭스로 고고??? 아니면 폭스탑??

**Comment by LSA31** [comment]
폭스로 고고!

**Comment by Hyunjiiing** [comment]
집나간 지웅씨를 찾습니다

**Comment by KangJiUng** [comment]
오케이 그럼 우리 앱이름은

### 폭스(Fox)

**Comment by LSA31** [comment]
넵 좋습니당

**Comment by Hyunjiiing** [comment]
근데 메세지 삭제햇는데 다 안보이는거죠 설마 나한테서만 삭제 이런건 아니겠지

**Comment by Hyunjiiing** [comment]
굳!!
