### ISSUE TITLE
firebase 연동 참고

### ISSUE THREAD

**Issue by KangJiUng** [Hyunjiiing/OSS-TeamProject2#62]
firebase 연동 시도하면서 구글링했던 링크들입니다. 생각보다 다양해서 방법도 비슷하게 통일하면 좋을 것 같아서 공유합니다.

**Comment by KangJiUng** [comment]
https://brunch.co.kr/@mystoryg/160
https://firebase.google.com/docs/flutter/setup?hl=ko&platform=ios
https://fjdkslvn.tistory.com/5
https://fjdkslvn.tistory.com/2
https://inforefine.com/%ED%94%8C%EB%9F%AC%ED%84%B0-3-0-%EC%97%85%EB%8D%B0%EC%9D%B4%ED%8A%B8-%EC%9D%B4%ED%9B%84-%ED%8C%8C%EC%9D%B4%EC%96%B4%EB%B2%A0%EC%9D%B4%EC%8A%A4-%EC%97%B0%EB%8F%99%ED%95%98%EA%B8%B0-2-2/

**Comment by Hyunjiiing** [comment]
굳굳!!
