### ISSUE TITLE
REAME파일 내용

### ISSUE THREAD

**Issue by Hyunjiiing** [Hyunjiiing/OSS-TeamProject2#64]
프로젝트 관리 배점표에 나와있는 README파일 내용입니다.
라이선스는 다소 엄격하지 않은 MIT License가 좋을거 같아요!

[팀 점수] README.md 파일이 아래 내용을 충실히 포함하고 있는가? (최대 4점)

1) 설치 방법 (1점) 
2) 의존성 (1점) 
 - OS, library, … (버전 명시)
 - 다른 github 패키지 이용 시, 해당 패키지에 대한 의존성을 명시
 - 해당 패키지에 ‘Star’ 한개씩 박아주는 센스 ^^
3) 사용(실행) 방법 (1점) 
4) 라이선스 (논문의 경우 citation), 연락처(이메일) (1점)

**Comment by KangJiUng** [comment]
쪼금이지만 적어뒀던 게 참으로..아깝습니다.....

**Comment by Hyunjiiing** [comment]
의존성 관련하여 다들 사용하셨던 라이브러리나 api 패키지 다운한다고 yaml파일에 추가한 코드들을 알려주시면 좋을거같습니당

ex)
- Flutter sdk
- flutter_bloc: ^2.0.0
- equatable: ^1.2.5
- rxdart: ^0.25.0

**Comment by Hyunjiiing** [comment]
반영하여 README파일 적기를 완료하였습니다!
