### ISSUE TITLE
식단 등록 화면 PR

### ISSUE THREAD

**Issue by KangJiUng** [Hyunjiiing/OSS-TeamProject2#68]
식단 등록 화면 설문조사 구체화 및 DB 연동, UI 수정, 식단 기록(목록)화면 기능 조금 추가했습니다. 마무리하면서 수정 기능은 필요하면 고정시키고 아니면 빼는 걸로 할게요 보니까 수정 화면을 또 따로 만들어야 할 것 같아서 쪼금 번거로울 것 같더라구여...긁적

**Comment by Hyunjiiing** [comment]
식단 입력했던거 수정하는 화면이면 굳이 안해도 될지도?? 다이어트 앱 쓰면서 수정해본적이 없는거 같아여

**Comment by Hyunjiiing** [comment]
식단 입력했던거 수정하는 화면이면 굳이 안해도 될지도?? 다이어트 앱 쓰면서 수정해본적이 없는거 같아여
