### ISSUE TITLE
dart파일 디버그하는 법 참고

### ISSUE THREAD

**Issue by LSA31** [Hyunjiiing/OSS-TeamProject2#78]
dart파일이 여러 개일 때 디버그 하는 법 공유하겠습니다!

**Comment by LSA31** [comment]
안드로이드 스튜디오를 열고 프로젝트를 로드합니다.

디버그 구성 설정을 확인합니다. 이는 프로젝트 내에 있는 "android/app" 폴더의 "build.gradle" 파일에서 확인할 수 있습니다. 아래와 같은 코드가 있는지 확인해주세요:

프로젝트 내에서 디버그할 Dart 파일을 엽니다.

디버그 모드로 실행하기 위해 디버그 모드에서 실행할 수 있는 디바이스 (실제 장치 또는 에뮬레이터)를 선택합니다.

디버깅을 시작하기 위해 "디버그" 버튼을 클릭하거나 "Shift + F9"를 누릅니다.

디버거가 시작되고, 앱은 선택한 디바이스에서 실행됩니다.

코드 실행 중에 디버그 포인트를 설정하려면 디버그 포인트를 원하는 줄에 클릭하거나 "Ctrl + F8"을 눌러 설정할 수 있습니다.

앱이 디버그 모드로 실행되고, 디버그 포인트에 도달하면 실행이 중지되고 디버거 창이 열립니다. 여기에서 변수의 상태를 확인하고, 단계별로 코드를 실행하면서 문제를 분석할 수 있습니다.

디버깅을 계속 진행하거나, "F8"을 눌러 다음 디버그 포인트로 이동하거나, "Shift + F9"를 눌러 디버그 모드를 종료할 수 있습니다.

**Comment by Hyunjiiing** [comment]
우와 그런 기능이 있는지 모르고 그냥 다른 프로젝트 열어서 확인했었는데 감사합니당
