### ISSUE TITLE
월경 정보 적용에 대한 의견입니다.

### ISSUE THREAD

**Issue by KangJiUng** [Hyunjiiing/OSS-TeamProject2#8]
다이어트, 특히 폭식 방지를 차별성으로 둔 앱을 개발하고자 하기 때문에 월경은 캘린더에 직접 기간을 입력하고, 폭식을 할 타이밍을 예측하는 분석 요소에만 사용을 하고 굳이 월경 기간을 예측하는 기능은 넣지 않아도 충분할 것 같은데 어떻게 생각하시나용?? 편하게 말씀해주세욥

**Comment by Hyunjiiing** [comment]
오 저도 동의합니다 폭식예측 기능이 주이니까 월경기간 예측하지 않아도 될거같아용

**Comment by LSA31** [comment]
월경 기간을 예측하면 그에 맞춰서 폭식할 타이밍도 예측 가능한 거 아닌가용?

**Comment by Hyunjiiing** [comment]
맞아요 폭식할타이밍 예측할때 어차피 예측할거같긴한데 앱상에서 보여주지 말자 요런 얘기같습니다

**Comment by LSA31** [comment]
아아 좋습니당
