### ISSUE TITLE
체중 그래프 프로그램 디자인 보완 의견

### ISSUE THREAD

**Issue by LSA31** [Hyunjiiing/OSS-TeamProject2#80]
혹시 체중 그래프 프로그램 디자인 어떻게 보완하면 좋을 지 의견 있으신 분 계실까요?!

**Comment by KangJiUng** [comment]
저번에 보여주셨던 거에서 말하시는 건가용

**Comment by Hyunjiiing** [comment]
![image](https://github.com/Hyunjiiing/OSS-TeamProject2/assets/107828202/7099ae98-030d-4f5f-94bc-5a2b390dcd57)
요런느낌으로 보안해도 좋을거 같습니당

**Comment by LSA31** [comment]
넵 맞습니다! 
현지님이 보내주신 이미지 참고해서 수정해 보겠습니다
