### ISSUE TITLE
삭제된 브랜치 오류 예방

### ISSUE THREAD

**Issue by LSA31** [Hyunjiiing/OSS-TeamProject2#82]
캘린더뷰 프로그램 제작할 때 제가 PR하여 총 3번 삭제하였습니다.
혹시나 이에 따른 오류가 생길까봐 제가 제작한 브랜치명 적어두겠습니다!

**Comment by LSA31** [comment]
Feature_E_cview
Feature_E_wgraph
Feature_E_recipe

사용하는 브랜치는 총 3가지입니다!

**Comment by LSA31** [comment]
다른 팀원분들도 혹시 모르니 사용하는 브랜치 아래에 적어주시면 감사하겠습니다!

**Comment by Hyunjiiing** [comment]
네 확인하였습니다!
