### ISSUE TITLE
시연영상 제안

### ISSUE THREAD

**Issue by KangJiUng** [Hyunjiiing/OSS-TeamProject2#92]
현지님 시연영상에서 debug 표시 없애자는 의견 보고 반영해서 제 제안도 말씀드립니다. 우선 저희 처음 시작화면에서 여우 디자인도 우선 해야하고 그 이후로 메인화면-설정화면-캐릭터육성화면-식단기록 화면 및 기록리스트-캘린더뷰-체중그래프-하단바 사용 가능-폭식알림 기능 정도의 순서로 하면 깔끔하게 괜찮을 것 같습니다.

**Comment by KangJiUng** [comment]
아 다이어트 일일섭취칼로리량 계산하는 부분이 빠졌는데 이 부분은 하단바랑 폭식알림기능 사이에 넣으면 될 것 같습니다. 아무래도 예측 부분이 가장 중요해서 앞부분은 너무 자세히는 설명하지 않고, 끝에서 강조가 될 수 있도록 짜는 것이 좋을 듯 하네요.

**Comment by KangJiUng** [comment]
다른 의견이 있으신 분 언제든 의견 주세요 우선 이슈 열어두겠습니다!

**Comment by Hyunjiiing** [comment]
하단바가 레시피 추천 페이지를 포함하는 것일까요??

**Comment by KangJiUng** [comment]
그렇습니다

**Comment by LSA31** [comment]
메인화면-설정화면-캐릭터육성화면-식단기록 화면 및 기록리스트-체중그래프-하단바 사용 가능-폭식알림 기능

하단바 사용 가능 부분에서 레시피 추천 화면이랑 캘린더뷰 같이 보여주는 거로 하시는 거 어떤가요?

**Comment by LSA31** [comment]
메인화면-설정화면-캐릭터육성화면-식단기록 화면 및 기록리스트-캘린더뷰-체중그래프-일일 섭취량-하단바 사용 가능-폭식알림 기능

**Comment by Hyunjiiing** [comment]
메인 화면 UI에서 위에서 아래로 쭉 찍고 마지막에 push알림 시연 영상 찍기로 하였습니다!
