### ISSUE TITLE
화면 합치는 방법

### ISSUE THREAD

**Issue by LSA31** [Hyunjiiing/OSS-TeamProject2#93]
화면 마지막에 합칠 때 방법 참고하면 좋을 것 같습니다.

**Comment by LSA31** [comment]
1. 위젯 트리 구성: 다양한 Dart 파일에 있는 위젯을 조합하여 하나의 화면을 구성할 수 있습니다. 이 경우, 각 Dart 파일은 해당하는 위젯을 정의하고, 상위 위젯에서 이들을 조합하여 화면을 구성합니다

2. 페이지 라우팅: 다른 Dart 파일을 다른 화면으로 이동하면서 전환할 수 있습니다. 이는 일반적으로 앱 내에서 여러 화면 또는 페이지를 구현하는 데 사용됩니다. 페이지 라우팅은 네비게이션 스택을 관리하고 사용자의 탐색을 지원합니다.

3. 상태 관리 패턴 사용: 여러 Dart 파일 간에 데이터를 공유하고 상태를 관리하기 위해 상태 관리 패턴을 사용할 수 있습니다

**Comment by Hyunjiiing** [comment]
저도 참고하면 좋을 링크를 공유합니다!
참고링크) https://tmdfyd0807.tistory.com/82
