### ISSUE TITLE
기말 발표 스토리 및 역할 분담 회의

### ISSUE THREAD

**Issue by LSA31** [Hyunjiiing/OSS-TeamProject2#94]
기말 발표 스토리 및 역할 분담 회의 합시다.

**Comment by Hyunjiiing** [comment]
1) 필요성 
2) Problem
3) 차별성
4) Soultion
5) 추진 방법 및 일정
6) 결과물
7) 한계점, 개선방향

에 대해서 역할분배를 진행하면 좋을거 같습니다!

**Comment by LSA31** [comment]
분량 필요성 프로블롬 차별성 솔류션 결과물 완성도(데모영상 or 시연) 한계점 및 개선방향

**Comment by Hyunjiiing** [comment]
개인적으로 5) 추진 방법 및 일정 / 7) 한계점 및 개성방향은 분량을 간단하게 줄이고 
1)필요성 / 2) Problem / 3) 차별성 / 4) Soultion / 6) 결과물 위주로 발표하면 좋을거 같습니당

**Comment by LSA31** [comment]
좋습니당

**Comment by LSA31** [comment]
1,2, 3,4,5 6,7 이렇게나 1,2 3,4 5,6,7나누는 거 어떨까요?

**Comment by Hyunjiiing** [comment]
시연영상은 같이 만들기로 하였으니 
1,2   
3,4
5,6,7
가 좋은거 같습니다!

**Comment by LSA31** [comment]
그럼 발표시간은 영상 2분 정도로 잡고
각자 3분씩 하면 될까요??

**Comment by LSA31** [comment]
강지웅: 필요성/Problem
오현지: 차별성/Soultion
이승아: 추진 방법 및 일정/결과물/한계점, 개선방향

**Comment by LSA31** [comment]
개인당 2분20초씩 하시면 될 것 같습니다

**Comment by Hyunjiiing** [comment]
승아님은 영상 2분에다가 5번 7번의 분량이 다소 적으니(두개 합쳐서 30초정도) 저랑 지웅님이 3분 30초 내외로 발표한다고 생각하면 좋을거 같습니당

**Comment by LSA31** [comment]
넵 알겠습니다

**Comment by Hyunjiiing** [comment]
교수님께서 짧은 문장으로 효과적으로 전달할 수 있도록 발표하는게 좋다고 하셨으니까 발표대본 적을때 참고하면 좋을거 같아용
