### ISSUE TITLE
다음 회의 : 6월 10일 토요일 오후 5시 / 해와야하는 것

### ISSUE THREAD

**Issue by Hyunjiiing** [Hyunjiiing/OSS-TeamProject2#95]
[해와야하는것]
- 코드 다 짜오기
--------------------------------------------------------
[각자 틈틈이 할 것]
- 발표시간에 맞춰 대본과 ppt 만들기
   - 오현지, 강지웅 : 3분 20초
   - 이승아 : 30~45초 (영상 포함하면 + 2분)

**Comment by Hyunjiiing** [comment]
진행하다가 막히는 부분이나 더 추가할 부분있으면 말해주세용

**Comment by LSA31** [comment]
넵 알겠습니당!

**Comment by Hyunjiiing** [comment]
[발표파트]
강지웅 : 1) 필요성 , 2) Problem
오현지 : 3) 차별성, 4) Solution
이승아 : 5) 추진방법 및 일정 5) 결과물 6) 한계점 및 개선방향
